baseURL = "https://willfurnass.github.io/team-container"
languageCode = "en-gb"
title = "Team Container @ TUOS"
theme = "terminal"
[params]
  # show selector to switch language
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "green"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "RSE_Sheffield"
  site = "RSE_Sheffield"

[languages]
  [languages.en]
    languageName = "English"
    title = "Team Container"
    subtitle = "A meetup at the University of Sheffield"
    owner = "RSE Sheffield"
    keywords = ""
    copyright = "University of Sheffield 2020"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
  
    [languages.en.params.logo]
      logoText = "Team Container @ TUOS"
      logoHomeLink = "/"
  
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
